export const routes = [
  {
    id: 0,
    code: "01A",
    places: {
      Alpha: 1,
      Bravo: 2,
      Charlie: 3,
      Echo: 4,
      Golf: 5,
    },
  },
  {
    id: 1,
    code: "02B",
    places: {
      Alpha: 1,
      Delta: 2,
      Echo: 3,
      Foxtrot: 4,
      Golf: 5,
    },
  },
  {
    id: 2,
    code: "03C",
    places: {
      Charlie: 1,
      Delta: 2,
      Foxtrot: 3,
      Hotel: 4,
      India: 5,
    },
  },
  {
    id: 3,
    code: "04A",
    places: {
      Charlie: 1,
      Delta: 2,
      Echo: 3,
      Foxtrot: 4,
      Gold: 5,
    },
  },
  {
    id: 4,
    code: "04D",
    places: {
      Charlie: 1,
      Echo: 2,
      Foxtrot: 3,
      Gold: 4,
      India: 5,
    },
  },
  {
    id: 5,
    code: "06B",
    places: {
      Delta: 1,
      Hotel: 2,
      Juliet: 3,
      Kilo: 4,
      Lima: 5,
    },
  },
  {
    id: 6,
    code: "06D",
    places: {
      Delta: 1,
      Foxtrot: 2,
      Gold: 3,
      India: 4,
      Kilo: 5,
    },
  },
  {
    id: 7,
    code: "10C",
    places: {
      Foxtrot: 1,
      Gold: 2,
      Hotel: 3,
      India: 4,
      Juliet: 5,
    },
  },
  {
    id: 8,
    code: "10H",
    places: {
      Foxtrot: 1,
      Hotel: 2,
      Juliet: 3,
      Lima: 4,
      November: 5,
    },
  },
  {
    id: 9,
    code: "11A",
    places: {
      Foxtrot: 1,
      Golf: 2,
      Kilo: 3,
      Mike: 4,
      November: 5,
    },
  },
  {
    id: 10,
    code: "11B",
    places: {
      Foxtrot: 1,
      Gold: 2,
      Lima: 3,
      Oscar: 4,
      Papa: 5,
    },
  },
  {
    id: 11,
    code: "20A",
    places: {
      India: 1,
      Juliet: 2,
      November: 3,
      Papa: 4,
      Romeo: 5,
    },
  },
  {
    id: 12,
    code: "20C",
    places: {
      India: 1,
      Kilo: 2,
      Lima: 3,
      Mike: 4,
      Romeo: 5,
    },
  },
  {
    id: 13,
    code: "42C",
    places: {
      Juliet: 1,
      Kilo: 2,
      Lima: 3,
      Mike: 4,
      Oscar: 5,
    },
  },
  {
    id: 14,
    code: "42D",
    places: {
      Juliet: 1,
      November: 2,
      Oscar: 3,
      Quebec: 4,
      Romeo: 5,
    },
  },
  {
    id: 15,
    code: "04H",
    places: {
      "Busay": 1,
      "Cebu Veterance Drive": 2,
      "Marco Polo Hotel": 3,
      "Jy Square Mall": 4,
      "Sudlon": 5,
      "The Church of Christ of Latter Day Saints Temple": 6,
      "Lahug Brgy Hall": 7,
      "University of the Philippines": 8,
      "Harolds Hotel Cebu": 9,
      "Escario Central Mall": 10,
      "Cebu Provincial Capitol": 11,
      "Cebu Doctors University Hospital": 12,
      "Fuente Osmeña Circle": 13,
      "Robinsons Place": 14,
      "Crown Regency Hotel": 15,
      "Abellana Sports Complex": 16,
      "Social Security System SSS": 17,
      "GV Tower Hotel": 18,
      "University of Cebu": 19,
      "Panganiban St": 20,
      "Katipunan Lumber": 21,
      "Carbon Public Market": 22
    }
  },
  {
    id: 16,
    code: "17B",
    places: {
      "Apas": 1,
      "Terminal: Apas": 2,
      "Camp Lapu Lapu Elementary School": 3,
      "PNP Training Center Field": 4,
      "IT Park": 5,
      "University of Southern Philippines": 6,
      "Salinas Drive": 7,
      "Lahug": 8,
      "Terminal: Lahug": 9,
      "Jy Square Mall": 10,
      "Sudlon": 11,
      "The Church of Christ of Latter Day Saints Temple": 12,
      "Lahug Brgy Hall": 13,
      "University of the Philippines": 14,
      "Harolds Hotel Cebu": 15,
      "Escario Central Mall": 16,
      "Cebu Provincial Capitol": 17,
      "Cebu Doctors University Hospital": 18,
      "Robinsons Place": 19,
      "Crown Regency Hotel": 20,
      "Abellana Sports Complex": 21,
      "Social Security System SSS": 22,
      "GV Tower Hotel": 23,
      "Metro Colon": 24,
      "University of San Jose Recoletos": 25,
      "Magallanes St": 26,
      "Progreso St": 27,
      "Carbon Public Market": 28
    }
  },  
];
